# Detect Phishing URLs
### Capstone 3 - Preprocessing and Modeling
Michael Garber

#### High-Level Steps
1. Preprocessing
    1. Create dummy/indicator features for categorical variables
    2. Standardize/scale numeric features
    3. Train/Test Split 
2. Modeling
    1. Fit your models with a training dataset
    2. Review model outcomes — Iterate over additional models as needed.
    3. Identify the final model that you think is the best model for this project

In [3]:
# Import Libraries
import pandas as pd
import os
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import TargetEncoder     # requires scikit-learn 1.3 or greater
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, precision_recall_curve, auc
import keras
from keras import layers
import seaborn as sns
import matplotlib.pyplot as plt

#### Preprocessing

In [5]:
# Import Data set
dataDir = os.path.join('../data/interim/urlData_raw.csv')
urlData = pd.read_csv(dataDir)

C:\Users\MG-Laptop\AppData\Local\Temp\ipykernel_1560\2659773463.py:3: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  urlData = pd.read_csv(dataDir)


In [6]:
# add new useful feature: URL length
urlData['url_Length'] = urlData['url'].apply(len)

In [7]:
# Data Info
urlData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450175 entries, 0 to 450174
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Unnamed: 0        450175 non-null  int64 
 1   key_0             445854 non-null  object
 2   url               450175 non-null  object
 3   type              450175 non-null  object
 4   parsedUrl         450175 non-null  object
 5   urlPart_scheme    450175 non-null  object
 6   subDomain         379885 non-null  object
 7   domain            450167 non-null  object
 8   tld               445854 non-null  object
 9   urlPart_path      444917 non-null  object
 10  urlPart_query     65541 non-null   object
 11  urlPart_fragment  359 non-null     object
 12  tld_join          445854 non-null  object
 13  Domain            445451 non-null  object
 14  Type              445451 non-null  object
 15  TLD Manager       445451 non-null  object
 16  isIPaddress       450175 non-null  boo

**Additional data cleaning** - identify features that have **missing values** (that we ares till planning on keeping)
- subDomain
- domain
- tld
- urlPart_path
- urlPart_query
- urlPart_fragment
- Type
- TLD Manager    

In [9]:
# Additional data cleaning - set missing values to zero
values = {
    'subDomain': '0',
    'domain': '0',
    'tld': '0',
    'urlPart_path': '0',
    'urlPart_query': '0',
    'urlPart_fragment': '0',
    'Type': '0',
    'TLD Manager': '0'}

urlData = urlData.fillna(value=values)

In [10]:
# Data Info - checking NULLs again (key and tld will be dropped)
urlData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450175 entries, 0 to 450174
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Unnamed: 0        450175 non-null  int64 
 1   key_0             445854 non-null  object
 2   url               450175 non-null  object
 3   type              450175 non-null  object
 4   parsedUrl         450175 non-null  object
 5   urlPart_scheme    450175 non-null  object
 6   subDomain         450175 non-null  object
 7   domain            450175 non-null  object
 8   tld               450175 non-null  object
 9   urlPart_path      450175 non-null  object
 10  urlPart_query     450175 non-null  object
 11  urlPart_fragment  450175 non-null  object
 12  tld_join          445854 non-null  object
 13  Domain            445451 non-null  object
 14  Type              450175 non-null  object
 15  TLD Manager       450175 non-null  object
 16  isIPaddress       450175 non-null  boo

In [11]:
urlData.head()

Unnamed: 0 key_0                        url        type  \
0           0   com     https://www.google.com  legitimate   
1           1   com    https://www.youtube.com  legitimate   
2           2   com   https://www.facebook.com  legitimate   
3           3   com      https://www.baidu.com  legitimate   
4           4   org  https://www.wikipedia.org  legitimate   

                                           parsedUrl urlPart_scheme subDomain  \
0  ParseResult(scheme='https', netloc='www.google...          https       www   
1  ParseResult(scheme='https', netloc='www.youtub...          https       www   
2  ParseResult(scheme='https', netloc='www.facebo...          https       www   
3  ParseResult(scheme='https', netloc='www.baidu....          https       www   
4  ParseResult(scheme='https', netloc='www.wikipe...          https       www   

      domain  tld urlPart_path urlPart_query urlPart_fragment tld_join Domain  \
0     google  com            0             0                0      com   .com   
1    youtube  com            0             0                0      com   .com   
2   facebook  com            0             0                0      com   .com   
3      baidu  com            0             0                0      com   .com   
4  wikipedia  org            0             0                0      org   .org   

      Type                        TLD Manager  isIPaddress  isPhish_bool  \
0  generic  VeriSign Global Registry Services        False         False   
1  generic  VeriSign Global Registry Services        False         False   
2  generic  VeriSign Global Registry Services        False         False   
3  generic  VeriSign Global Registry Services        False         False   
4  generic     Public Interest Registry (PIR)        False         False   

   url_Length  
0          22  
1          23  
2          24  
3          21  
4          25

In [12]:
urlData.columns[:]

Index(['Unnamed: 0', 'key_0', 'url', 'type', 'parsedUrl', 'urlPart_scheme',
       'subDomain', 'domain', 'tld', 'urlPart_path', 'urlPart_query',
       'urlPart_fragment', 'tld_join', 'Domain', 'Type', 'TLD Manager',
       'isIPaddress', 'isPhish_bool', 'url_Length'],
      dtype='object')

**Value Counts - urlPart_scheme**

In [14]:
#urlData[['url', 'urlPart_scheme', 'subDomain', 'tld', 'domain', 'type', 'TLD Manager', 'isIPaddress', 'isPhish_bool']]
pd.DataFrame(urlData['urlPart_scheme'].value_counts())

count
urlPart_scheme        
https           352185
http             97947
httpss              35
ftp                  8

**Value Counts - subDomain**

In [16]:
pd.DataFrame(urlData['subDomain'].value_counts())

count
subDomain                                  
www                                  276100
0                                     70290
www.en                                13626
www.music                              1289
www.people                             1228
...                                     ...
www.ohv.parks                             1
www.ohtheplaceswewillgo-books             1
www.ohr                                   1
www.ohomen171s-journey-through-life       1
boasecg7                                  1

[32041 rows x 1 columns]

**Value Counts - TLD Manager**

In [18]:
urlData['TLD Manager'].value_counts()

TLD Manager
VeriSign Global Registry Services                                                                               333004
Public Interest Registry (PIR)                                                                                   38393
Canadian Internet Registration Authority (CIRA) Autorité Canadienne pour les enregistrements Internet (ACEI)     10086
EDUCAUSE                                                                                                          6976
Nominet UK                                                                                                        5997
                                                                                                                 ...  
AS Domain Registry                                                                                                   1
University of Swaziland Department of Computer Science                                                               1
Dot London Domains Limited          

**Determine how to handle categorical features**

In [20]:
# Let's see cardinality / # of uniques for each feature - use to determine categorical fields to dummy and how to encode - one-hot vs label
urlData[['key_0', 'url', 'type', 'parsedUrl', 'urlPart_scheme',
       'subDomain', 'domain', 'tld', 'urlPart_path', 'urlPart_query',
       'urlPart_fragment', 'tld_join', 'Domain', 'Type', 'TLD Manager',
       'isIPaddress', 'isPhish_bool']].describe()

key_0                     url        type  \
count   445854                  450175      450175   
unique     415                  450175           2   
top        com  https://www.google.com  legitimate   
freq    316414                       1      345738   

                                                parsedUrl urlPart_scheme  \
count                                              450175         450175   
unique                                             450132              4   
top     ParseResult(scheme='http', netloc='new.sosnovs...          https   
freq                                                    2         352185   

       subDomain     domain     tld urlPart_path urlPart_query  \
count     450175     450175  450175       450175        450175   
unique     32041     130747     832       317144         55325   
top          www  wikipedia     com            /             0   
freq      276100      12895  316414        55253        384636   

       urlPart_fragment tld_join  Domain     Type  \
count            450175   445854  445451   450175   
unique               72      415     360        5   
top                   0      com    .com  generic   
freq             449816   316414  316414   376803   

                              TLD Manager isIPaddress isPhish_bool  
count                              450175      450175       450175  
unique                                260           2            2  
top     VeriSign Global Registry Services       False        False  
freq                               333004      447309       345738

> - Will use **mean encoding** for the **high cardinality columns** (e.x. domain) as using one-hot would create too many columns and with sparse data
> - Will **mean encode after train/test splitting** to **avoid data leakage**

In [22]:
# Select/Drop features - create new dataframe for this major data change
urlDataV2 = urlData.drop(['Unnamed: 0', 'key_0', 'url', 'type', 'parsedUrl', 'tld_join', 'Domain'], axis=1)

In [23]:
# View new DF
urlDataV2.head()

urlPart_scheme subDomain     domain  tld urlPart_path urlPart_query  \
0          https       www     google  com            0             0   
1          https       www    youtube  com            0             0   
2          https       www   facebook  com            0             0   
3          https       www      baidu  com            0             0   
4          https       www  wikipedia  org            0             0   

  urlPart_fragment     Type                        TLD Manager  isIPaddress  \
0                0  generic  VeriSign Global Registry Services        False   
1                0  generic  VeriSign Global Registry Services        False   
2                0  generic  VeriSign Global Registry Services        False   
3                0  generic  VeriSign Global Registry Services        False   
4                0  generic     Public Interest Registry (PIR)        False   

   isPhish_bool  url_Length  
0         False          22  
1         False          23  
2         False          24  
3         False          21  
4         False          25

**Features to One-Hot encode**
- 'urlPart_scheme'
- 'Type'
- 'isIPaddress'
- 'isPhish_bool'

*...because they are lower cardinality*

In [25]:
# Let's rename "type" to a more descriptive name before encoding
urlDataV2 = urlDataV2.rename(columns={'Type':'TLD_type'})

##### Create dummies \ one-hot encode

In [27]:
# One-Hot encode features
urlDataV2 = pd.get_dummies(urlDataV2, columns=['urlPart_scheme', 'TLD_type'])

In [28]:
# view new DF
urlDataV2.head()

subDomain     domain  tld urlPart_path urlPart_query urlPart_fragment  \
0       www     google  com            0             0                0   
1       www    youtube  com            0             0                0   
2       www   facebook  com            0             0                0   
3       www      baidu  com            0             0                0   
4       www  wikipedia  org            0             0                0   

                         TLD Manager  isIPaddress  isPhish_bool  url_Length  \
0  VeriSign Global Registry Services        False         False          22   
1  VeriSign Global Registry Services        False         False          23   
2  VeriSign Global Registry Services        False         False          24   
3  VeriSign Global Registry Services        False         False          21   
4     Public Interest Registry (PIR)        False         False          25   

   urlPart_scheme_ftp  urlPart_scheme_http  urlPart_scheme_https  \
0               False                False                  True   
1               False                False                  True   
2               False                False                  True   
3               False                False                  True   
4               False                False                  True   

   urlPart_scheme_httpss  TLD_type_0  TLD_type_country-code  TLD_type_generic  \
0                  False       False                  False              True   
1                  False       False                  False              True   
2                  False       False                  False              True   
3                  False       False                  False              True   
4                  False       False                  False              True   

   TLD_type_generic-restricted  TLD_type_sponsored  
0                        False               False  
1                        False               False  
2                        False               False  
3                        False               False  
4                        False               False

*Note: Due to use of **Target encoding**, we will **preprocess** data in a **modified order**...

    1. train/test split data
    2. target encode data
    3. Scale data

In [30]:
# one more peek at columns and object types
urlDataV2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450175 entries, 0 to 450174
Data columns (total 19 columns):
 #   Column                       Non-Null Count   Dtype 
---  ------                       --------------   ----- 
 0   subDomain                    450175 non-null  object
 1   domain                       450175 non-null  object
 2   tld                          450175 non-null  object
 3   urlPart_path                 450175 non-null  object
 4   urlPart_query                450175 non-null  object
 5   urlPart_fragment             450175 non-null  object
 6   TLD Manager                  450175 non-null  object
 7   isIPaddress                  450175 non-null  bool  
 8   isPhish_bool                 450175 non-null  bool  
 9   url_Length                   450175 non-null  int64 
 10  urlPart_scheme_ftp           450175 non-null  bool  
 11  urlPart_scheme_http          450175 non-null  bool  
 12  urlPart_scheme_https         450175 non-null  bool  
 13  urlPart_scheme

##### EDA: Feature correlation

In [32]:
# feature correlations (excluding non-numerics)
pd.DataFrame(urlDataV2.corrwith(other=urlDataV2['isPhish_bool'], numeric_only=True).sort_values(ascending=False))

0
isPhish_bool                 1.000000
urlPart_scheme_http          0.959467
TLD_type_country-code        0.338015
TLD_type_0                   0.175337
isIPaddress                  0.145640
url_Length                   0.085058
TLD_type_generic-restricted  0.070401
urlPart_scheme_ftp           0.006422
urlPart_scheme_httpss       -0.004846
TLD_type_sponsored          -0.077846
TLD_type_generic            -0.332983
urlPart_scheme_https        -0.959277

> **Top feature correlations to target**
> - urlPart_scheme_http**s** &emsp;&emsp;(~-96%)
> - urlPart_scheme_http &emsp;&emsp; (~+96%) 

Woah! The **url scheme** (specifically the use of **'http'** or **'https'**) is *highly* predictive of the target in this data set.


In [34]:
pd.DataFrame(urlDataV2[['urlPart_scheme_ftp', 'urlPart_scheme_http', 'urlPart_scheme_https', 'urlPart_scheme_httpss', 'isPhish_bool']].value_counts())

count
urlPart_scheme_ftp urlPart_scheme_http urlPart_scheme_https urlPart_scheme_httpss isPhish_bool        
False              False               True                 False                 False         345702
                   True                False                False                 True           97947
                   False               True                 False                 True            6483
                                       False                True                  False             35
True               False               False                False                 True               7
                                                                                  False              1

> When the scheme is 'https', the URL **is** phishing     - 345702 times \
> When the scheme is 'http',  the URL is **not** phishing - 97947  times \
> URL scheme of 'http' or 'https' predicts the target value in over **98%** of rows in this data set!

In [36]:
# Calculate percentage of URLs that can be accurately classified solely via their urlPart_scheme*
#      https    http     total record count
print((345702 + 97947) / 450175.0)

0.9855034153384795


##### Train/Test Split

In [38]:
# assign X & y
X = urlDataV2.drop(columns=['isPhish_bool'], axis=1).copy()
y = urlDataV2['isPhish_bool'].copy()

# perform train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

##### Target/Mean Encode
> https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.TargetEncoder.html#sklearn.preprocessing.TargetEncoder

In [40]:
# target encode (using auto-smoothing and cross-fitting)
targetEncoderAuto = TargetEncoder(smooth='auto')
colsToEncode = ['subDomain', 'domain', 'tld', 'urlPart_path', 'urlPart_query', 'urlPart_fragment', 'TLD Manager']

X_train_encoded = X_train.copy()
X_test_encoded  = X_test.copy()
X_train_encoded[colsToEncode] = targetEncoderAuto.fit_transform(X_train[colsToEncode], y_train)
X_test_encoded[colsToEncode]  = targetEncoderAuto.transform(X_test[colsToEncode])

In [41]:
# Check encoding results
pd.DataFrame(X_train_encoded).head()

subDomain    domain       tld  urlPart_path  urlPart_query  \
109475   0.047118  0.000000  0.092339      0.231991       0.220880   
360352   0.995370  1.000000  1.000000      0.231991       0.220411   
133254   0.047513  0.000000  0.161813      0.231995       0.220713   
175455   0.047118  0.000000  0.010315      0.109004       0.000000   
392895   1.000000  0.389498  0.794975      0.231991       0.220411   

        urlPart_fragment  TLD Manager  isIPaddress  url_Length  \
109475          0.231381     0.092339        False          62   
360352          0.231316     0.959602        False         109   
133254          0.231350     0.169619        False          68   
175455          0.231381     0.065209        False          36   
392895          0.231316     0.569120        False          46   

        urlPart_scheme_ftp  urlPart_scheme_http  urlPart_scheme_https  \
109475               False                False                  True   
360352               False                 True                 False   
133254               False                False                  True   
175455               False                False                  True   
392895               False                 True                 False   

        urlPart_scheme_httpss  TLD_type_0  TLD_type_country-code  \
109475                  False       False                  False   
360352                  False       False                   True   
133254                  False       False                  False   
175455                  False       False                   True   
392895                  False       False                  False   

        TLD_type_generic  TLD_type_generic-restricted  TLD_type_sponsored  
109475              True                        False               False  
360352             False                        False               False  
133254              True                        False               False  
175455             False                        False               False  
392895             False                         True               False

> Encoding on columns 1-7 ('subDomain' to 'TLD Manager') looks good

##### Standardize and Scale

In [44]:
# MinMax Scale the data
scaler = MinMaxScaler()
scaler.fit(X_train_encoded)

X_train_preprocessed = scaler.transform(X_train_encoded)
X_test_preprocessed  = scaler.transform(X_test_encoded)

In [45]:
# Check scaling results
X_test_pp_DF = pd.DataFrame(X_test_preprocessed)  # make DF version X_test_preprocessed
X_test_pp_DF.head()

0         1         2         3         4         5         6    7   \
0  0.000000  0.000000  0.003428  0.231993  0.220613  0.000051  0.003428  0.0   
1  0.047212  0.000000  0.091958  0.231993  0.220613  0.000051  0.091958  0.0   
2  0.047212  0.231993  0.161421  0.109466  0.220613  0.000051  0.169260  0.0   
3  0.995200  0.231993  0.609738  0.231993  0.220613  0.000051  0.626788  0.0   
4  0.047212  0.231993  0.319154  0.231993  0.220613  0.000051  0.169260  0.0   

         8    9    10   11   12   13   14   15   16   17  
0  0.014129  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  
1  0.028781  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  
2  0.008373  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  
3  0.010466  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
4  0.060701  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0

In [46]:
X_test_pp_DF.describe()

0              1              2              3   \
count  112544.000000  112544.000000  112544.000000  112544.000000   
mean        0.225627       0.213279       0.232026       0.266458   
std         0.368164       0.350663       0.227334       0.238814   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.047212       0.000000       0.161421       0.231993   
50%         0.047212       0.000000       0.161421       0.231993   
75%         0.047212       0.231993       0.161421       0.231993   
max         1.000000       1.000000       1.000000       1.000000   

                  4              5              6              7   \
count  112544.000000  112544.000000  112544.000000  112544.000000   
mean        0.235319       0.000584       0.232376       0.006540   
std         0.108339       0.023082       0.222231       0.080604   
min         0.000000       0.000051       0.000000       0.000000   
25%         0.220613       0.000051       0.169260       0.000000   
50%         0.220613       0.000051       0.169260       0.000000   
75%         0.220613       0.000051       0.169260       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

                  8              9              10             11  \
count  112544.000000  112544.000000  112544.000000  112544.000000   
mean        0.027310       0.000018       0.217533       0.782361   
std         0.019964       0.004216       0.412570       0.412643   
min         0.002093       0.000000       0.000000       0.000000   
25%         0.016745       0.000000       0.000000       1.000000   
50%         0.023025       0.000000       0.000000       1.000000   
75%         0.032967       0.000000       0.000000       1.000000   
max         1.206698       1.000000       1.000000       1.000000   

                  12             13             14             15  \
count  112544.000000  112544.000000  112544.000000  112544.000000   
mean        0.000089       0.010698       0.127523       0.836117   
std         0.009426       0.102877       0.333560       0.370171   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       1.000000   
50%         0.000000       0.000000       0.000000       1.000000   
75%         0.000000       0.000000       0.000000       1.000000   
max         1.000000       1.000000       1.000000       1.000000   

                  16             17  
count  112544.000000  112544.000000  
mean        0.003536       0.022125  
std         0.059363       0.147090  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000

#### Modeling

In [48]:
# Get Dataset Shape
X_shape = X_train_preprocessed.shape[1]
X_shape

18

In [70]:
# create model functions
def createModel(optimizer='adam', X_shape = X_shape, numLayers = 0, numNodes = [0]):
    model = keras.Sequential()
    model.add(keras.Input(shape=(X_shape,)))
    # loop here
    for layer in range(numLayers):
        model.add(layers.Dense(numNodes[layer], activation='relu'))
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['Recall'])
    return model

In [82]:
# test function
model_basic = createModel(numLayers = 1, numNodes = [1])
model_basic.summary()

model_mid   = createModel(numLayers = 3, numNodes = [3,3,3])
model_mid.summary()

model_heavy = createModel(numLayers = 5, numNodes = [4,1,6,2,3])
model_heavy.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 1)                   │              19 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21 (84.00 B)

 Trainable params: 21 (84.00 B)

 Non-trainable params: 0 (0.00 B)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                      │ (None, 3)                   │              57 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 3)                   │              12 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 3)                   │              12 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 85 (340.00 B)

 Trainable params: 85 (340.00 B)

 Non-trainable params: 0 (0.00 B)

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                     │ (None, 4)                   │              76 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │               5 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 6)                   │              12 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 2)                   │              14 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 3)                   │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 120 (480.00 B)

 Trainable params: 120 (480.00 B)

 Non-trainable params: 0 (0.00 B)